### ISSUE TITLE
Root composer.json requires notihnio/php-mutlipart-form-data-parser, it could not be found in any version, there may be a typo in the package name

### ISSUE THREAD

**Issue by akzone** [notihnio/php-mutlipart-form-data-parser#2]
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by notihnio** [comment]
Hi thanks for reporting. I cannot reproduce the issue.
